name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: windows-19
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 7a2a6e1728da40ccdfd9d318f4faf813298c0b28

    - name: Build C Code
      run: msbuild /t:build Sandboxie\Sandbox.sln /p:Configuration="SbieRelease" /p:Platform=x64 -maxcpucount:8
